### PR TITLE
Remaining virtual guests CRUD changes

### PR DESCRIPTION
**Pull request by igoonich**
Changes with respect to issue https://github.com/TheWeatherCompany/terraform/issues/5. Should be merged befor that issue.

### CODE REVIEW

**Comment by danielcbright** [comment]
Ivan, the PR to maximilian/softlayer-go is failing:
https://travis-ci.org/maximilien/softlayer-go/builds/95575499 can you
please take a look?

I've already changed the github paths back to normal.

-Daniel

On Thu, Dec 3, 2015 at 12:50 PM, Ivan Goonich notifications@github.com
wrote:

> Changes with respect to issue TheWeatherCompany/terraform#5
> https://github.com/TheWeatherCompany/terraform/issues/5. Should be
> 
> ## merged befor that issue.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/TheWeatherCompany/softlayer-go/pull/6
> Commit Summary
> - https://github.com/TheWeatherCompany/terraform/issues/5 Add
>   hourly_billing_flag attribute to VirtualGuest struct
> - fix tiny error
> - https://github.com/TheWeatherCompany/terraform/issues/5 add
>   hourlyBillingFlag to getObject::objectMask
> - https://github.com/TheWeatherCompany/terraform/issues/5
>   LocalDiskFlag and BlockDeviceTemplateGroup were added to VirtualGuest struct
> - #4 Add an option to fetch frontend and backend network IDs
> - tiny code fix
> - #4 Include functionality to upgrade "ram", "cpus" and
>   "public_network_speed" of virtual servers
> - #4 Remove debug logging
> - #4 Tiny changes in the imports
> - #4 Tiny changes upgrade method
> 
> File Changes
> - _M_ data_types/softlayer_item_price.go
>   https://github.com/TheWeatherCompany/softlayer-go/pull/6/files#diff-0
>   (1)
> - _A_ data_types/softlayer_product_package.go
>   https://github.com/TheWeatherCompany/softlayer-go/pull/6/files#diff-1
>   (20)
> - _M_ data_types/softlayer_virtual_guest.go
>   https://github.com/TheWeatherCompany/softlayer-go/pull/6/files#diff-2
>   (10)
> - _M_ services/softlayer_product_package.go
>   https://github.com/TheWeatherCompany/softlayer-go/pull/6/files#diff-3
>   (98)
> - _M_ services/softlayer_virtual_guest.go
>   https://github.com/TheWeatherCompany/softlayer-go/pull/6/files#diff-4
>   (148)
> - _M_ softlayer/softlayer_product_package_service.go
>   https://github.com/TheWeatherCompany/softlayer-go/pull/6/files#diff-5
>   (5)
> - _M_ softlayer/softlayer_virtual_guest_service.go
>   https://github.com/TheWeatherCompany/softlayer-go/pull/6/files#diff-6
>   (12)
> 
> Patch Links:
> - https://github.com/TheWeatherCompany/softlayer-go/pull/6.patch
> - https://github.com/TheWeatherCompany/softlayer-go/pull/6.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheWeatherCompany/softlayer-go/pull/6.

## 
- Daniel **Bright  *|Sr. Systems Engineer - Architecture & Platforms (Grid)
- w:\* 770.226.2840 _e:_ daniel.bright@weather.com

**Comment by igoonich** [comment]
Hi @danielcbright,

According to travis logs go failed while fetching library `godep`. So it seems it is not actually related to our chnages:
image

Can I restart this travis job somehow to be sure that it is not a temporary issue, because I cannot reproduce it locally?

**Comment by danielcbright** [comment]
I can do another PR later today and test, thanks for pointing that out Ivan

On Tue, Dec 8, 2015 at 10:32 AM, Ivan Goonich notifications@github.com
wrote:

> Hi @danielcbright https://github.com/danielcbright,
> 
> According to travis logs go failed while fetching library godep. So it
> seems it is not actually related to our chnages:
> [image: image]
> https://cloud.githubusercontent.com/assets/5939328/11659524/b8608b98-9dd9-11e5-880e-10792643e148.png
> 
> Can I restart this travis job somehow to be sure that it is not a
> temporary issue, because I cannot reproduce it locally?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheWeatherCompany/softlayer-go/pull/6#issuecomment-162916707
> .

## 
- Daniel **Bright  *|Sr. Systems Engineer - Architecture & Platforms (Grid)
- w:\* 770.226.2840 _e:_ daniel.bright@weather.com

**Comment by igoonich** [comment]
@danielcbright, I've created one more PR. There might be a warning at stage `Vetting packages for potential issues...` for one of the fields as soon as Travis succeeds to fetch `godep`. This PR will resolve that warning - https://github.com/TheWeatherCompany/softlayer-go/pull/11.

**Comment by danielcbright** [comment]
Same error unfortunately:
https://travis-ci.org/maximilien/softlayer-go/builds/95639957

On Tue, Dec 8, 2015 at 10:50 AM, Ivan Goonich notifications@github.com
wrote:

> @danielcbright https://github.com/danielcbright, I've created one more
> PR. There might be a warning at stage Vetting packages for potential
> issues... for one of the fields as soon as Travis succeeds to fetch godep.
> This PR will resolve that warning - #11
> https://github.com/TheWeatherCompany/softlayer-go/pull/11.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheWeatherCompany/softlayer-go/pull/6#issuecomment-162923921
> .

## 
- Daniel **Bright  *|Sr. Systems Engineer - Architecture & Platforms (Grid)
- w:\* 770.226.2840 _e:_ daniel.bright@weather.com

**Comment by igoonich** [comment]
Hi @danielcbright,

I've just checked the following tab of other latest Travis builds of `softlayer-go`and it has the same errors with `godep`: 
https://travis-ci.org/maximilien/softlayer-go/builds

So, it looks like the same building error appeared even 13 hours ago for another [builds of maximilien](https://travis-ci.org/maximilien/softlayer-go/builds/95515300). As far as I understand, it is not actually related to our latest PR, but to TravisCI `softlayer-go` building environment itself. 

Probably `GOPATH` is wrongly configured there, as it fails to find `build.MultiplePackageError`.

**Pull request merged**
